(defprotocol GraphDBAPI
  (add-edge [this src dst] [this src dst attrs] [this src dst label attrs])
  (add-vertex [this] [this attrs])
  (backup [this] [this path])
  (closed? [this])
  (commit [this])
  (configuration [this])
  (create-index [this data-type] [this data-type id])
  (cypher [this query-str])
  (disconnect [this])
  (dump [this])
  (edges [this] [this ids])
  (explain [this query-str])
  (features [this])
  (flush [this])
  (get-edge [this id])
  (get-edges [this])
  (get-relations [this])
  (get-vertex [this id])
  (get-vertex-relations [this id])
  (get-vertices [this])
  (get-vertices-relations [this ids])
  (graph-name [this])
  (open? [this])
  (remove-edge [this id])
  (remove-relation [this rid vid])
  (remove-relations [this vid])
  (remove-vertex [this id])
  (rollback [this])
  (show-features [this])
  (tx [this])
  (variables [this])
  (vertices [this] [this ids]))
